// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzco3SgwGxXMypDOSjWBjc0-aFn0kHytg',
    appId: '1:69819879765:web:2b2db7556a75506b25dfdc',
    messagingSenderId: '69819879765',
    projectId: 'taskapp-d2f33',
    authDomain: 'taskapp-d2f33.firebaseapp.com',
    storageBucket: 'taskapp-d2f33.appspot.com',
    measurementId: 'G-9533RRZ0KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRNIMBTvGJlh4wx1R1VT4v7JK_8ym9ng',
    appId: '1:69819879765:android:9c579ce49891d0f425dfdc',
    messagingSenderId: '69819879765',
    projectId: 'taskapp-d2f33',
    storageBucket: 'taskapp-d2f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9eLUmfp0QECjQd1ZSS736x71F2KLfkY',
    appId: '1:69819879765:ios:8579005f3a452d6225dfdc',
    messagingSenderId: '69819879765',
    projectId: 'taskapp-d2f33',
    storageBucket: 'taskapp-d2f33.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU9eLUmfp0QECjQd1ZSS736x71F2KLfkY',
    appId: '1:69819879765:ios:cfbee4ef21ba367525dfdc',
    messagingSenderId: '69819879765',
    projectId: 'taskapp-d2f33',
    storageBucket: 'taskapp-d2f33.appspot.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
